# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  vpn_bot:
    # Сборка образа для сервиса из директории
    build: VPN_by_Prokin/
    # Задание имени контейнера для сервиса
    container_name: python_bot
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/bot-logs:/opt/logs
    networks:
      - proxynet

networks:
  proxynet:
    name: vpn_bot_default
    external: true