# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  vpn_bot:
    # Сборка образа для сервиса из директории
    build: main/
    # Задание имени контейнера для сервиса
    container_name: python_bot
    volumes:
      - /etc/localtime:/etc/localtime