# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: work
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ghj445544
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



  vpn_bot:
    # Сборка образа для сервиса из директории
    build: VPN_by_Prokin/
    # Задание имени контейнера для сервиса
    container_name: python_bot
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/bot-logs:/opt/logs
    networks:
      - proxynet

volumes:
  postgres_data:
  
networks:
  proxynet:
    name: vpn_bot_default
    external: true