---
telegram:
  api: "6577838059:AAHYKrSVEPZVg9DKHEBEO9lWT_DBznUNeqc"

outline:
  api: "https://95.169.181.151:34466/QJTInLnpDhvy4abdgS0aUQ/"

database:
  host: 192.168.0.194
  port: 5432
  user: postgres
  pass: Ghj445544
  base_name: work_test

logs:
  dir: /tmp/test