---
telegram:
  api: "telegram-api"
  admin_id: 758952233

providers:
  yookassa: '****token_from_TG****'

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  pass: password
  base_name: work_test

logs:
  dir: /var/log/vpn-bot-test
