---
telegram:
  api: "5779279148:AAGot2SPqlcKnT6qmTUcUnDFwMMR_ySbJ5Y"
  admin_id: 758952233

outline:
  api: "https://95.169.181.151:34466/QJTInLnpDhvy4abdgS0aUQ/"

database:
  host: 192.168.0.194
  port: 5432
  user: postgres
  pass: Ghj445544
  base_name: work

logs:
  dir: /tmp
