---
telegram:
  api: "6577838059:AAHYKrSVEPZVg9DKHEBEO9lWT_DBznUNeqc"

outline:
  api: "https://95.169.181.151:34466/QJTInLnpDhvy4abdgS0aUQ/"

database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  pass: 123
  base_name: vpndb

logs:
  dir: /tmp